### ISSUE TITLE
Running instructions

### ISSUE THREAD

**Issue by drewstone** [paritytech/substrate-analytics#48]
How does one set this up against a local or remote substrate node? Running `cargo run` or building a release and running doesn't seem to start this service.

Gonna keep reading through the docs but some more clarity on running against a local chain would be helpful :)!

**Comment by mattrutherford** [comment]
So, with a local chain, you just need to start substrate with the following cli parameters:

`--telemetry-url ws://localhost:8080 9` where last digit is the level of verbosity, 9 being highest.

Additionally if you want to capture the output from substrate tracing, you need the following arguments when starting substrate:

`--tracing-receiver telemetry`
`--tracing-targets sc=trace,sp=trace,frame=trace,pallet=trace`

The above params will give you the profiling data for all dispatchable functions from the native runtime, along with any additional tracing in client or primitives.

I will update the README with some more info soon, but feel free to ask any more specific questions here

**Comment by mattrutherford** [comment]
If you navigate to http://localhost:8080/dashboard/node there's a realtime graph of the profiling data. Will be adding more dashboards soon...

![Screenshot 2020-03-24 at 13 35 40](https://user-images.githubusercontent.com/44339188/77431476-a8c1f800-6dd4-11ea-85c8-60f99f4f804f.png)

**Comment by dvdplm** [comment]
@drewstone I will close this now, feel free to comment here if you have further questions. :)
